# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserdefinedMenu_v2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 559)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 18)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_instructions = QtWidgets.QLabel(self.centralwidget)
        self.lbl_instructions.setObjectName("lbl_instructions")
        self.horizontalLayout_3.addWidget(self.lbl_instructions)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 20, -1, 20)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_lcp = QtWidgets.QLabel(self.centralwidget)
        self.lbl_lcp.setObjectName("lbl_lcp")
        self.gridLayout.addWidget(self.lbl_lcp, 1, 0, 1, 1)
        self.lbl_rcp = QtWidgets.QLabel(self.centralwidget)
        self.lbl_rcp.setObjectName("lbl_rcp")
        self.gridLayout.addWidget(self.lbl_rcp, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, 20, -1, 20)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setVerticalSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spin_occ_duration = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_occ_duration.setDecimals(0)
        self.spin_occ_duration.setMaximum(1000.0)
        self.spin_occ_duration.setProperty("value", 10.0)
        self.spin_occ_duration.setObjectName("spin_occ_duration")
        self.gridLayout_2.addWidget(self.spin_occ_duration, 0, 1, 1, 1)
        self.spin_bandfreq = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_bandfreq.setMaximum(30000)
        self.spin_bandfreq.setProperty("value", 8400)
        self.spin_bandfreq.setObjectName("spin_bandfreq")
        self.gridLayout_2.addWidget(self.spin_bandfreq, 3, 1, 1, 1)
        self.spin_lowest_alt = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_lowest_alt.setDecimals(0)
        self.spin_lowest_alt.setMaximum(100000.0)
        self.spin_lowest_alt.setObjectName("spin_lowest_alt")
        self.gridLayout_2.addWidget(self.spin_lowest_alt, 2, 1, 1, 1)
        self.spin_eq_radius = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_eq_radius.setDecimals(0)
        self.spin_eq_radius.setMaximum(100000.0)
        self.spin_eq_radius.setObjectName("spin_eq_radius")
        self.gridLayout_2.addWidget(self.spin_eq_radius, 1, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_occ_duration = QtWidgets.QLabel(self.centralwidget)
        self.lbl_occ_duration.setObjectName("lbl_occ_duration")
        self.horizontalLayout_6.addWidget(self.lbl_occ_duration)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_eq_radius = QtWidgets.QLabel(self.centralwidget)
        self.lbl_eq_radius.setObjectName("lbl_eq_radius")
        self.horizontalLayout_7.addWidget(self.lbl_eq_radius)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lbl_lowest_alt = QtWidgets.QLabel(self.centralwidget)
        self.lbl_lowest_alt.setObjectName("lbl_lowest_alt")
        self.horizontalLayout_8.addWidget(self.lbl_lowest_alt)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lbl_bandfreq = QtWidgets.QLabel(self.centralwidget)
        self.lbl_bandfreq.setObjectName("lbl_bandfreq")
        self.horizontalLayout_9.addWidget(self.lbl_bandfreq)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btn_continue = QtWidgets.QPushButton(self.centralwidget)
        self.btn_continue.setMinimumSize(QtCore.QSize(120, 0))
        self.btn_continue.setObjectName("btn_continue")
        self.horizontalLayout_2.addWidget(self.btn_continue)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(7, 10)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_back.setText(_translate("MainWindow", "Back"))
        self.lbl_instructions.setText(_translate("MainWindow", "For instructions on how to format User-Defined data files,\n"
"please see the User\'s Guide."))
        self.lbl_lcp.setText(_translate("MainWindow", "Select the LCP data file:"))
        self.lbl_rcp.setText(_translate("MainWindow", "Select the RCP data file:"))
        self.label.setText(_translate("MainWindow", "Enter intitial values for the following acquisition geometry parameters.\n"
"You will be able to adjust these on the Signal Processing window."))
        self.lbl_occ_duration.setText(_translate("MainWindow", "Occultation Duration (min)"))
        self.lbl_eq_radius.setText(_translate("MainWindow", "Equatorial Radius (km)"))
        self.lbl_lowest_alt.setText(_translate("MainWindow", "Lowest Altitude (km)"))
        self.lbl_bandfreq.setText(_translate("MainWindow", "Band Frequency (MHz)"))
        self.btn_continue.setText(_translate("MainWindow", "Continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

