# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignalAnalysis_v15.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1325, 921)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vlayout_left = QtWidgets.QVBoxLayout()
        self.vlayout_left.setObjectName("vlayout_left")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_7.addWidget(self.btn_back)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.vlayout_left.addLayout(self.horizontalLayout_7)
        self.group_aq_geometry = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.group_aq_geometry.setFont(font)
        self.group_aq_geometry.setAlignment(QtCore.Qt.AlignCenter)
        self.group_aq_geometry.setObjectName("group_aq_geometry")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.group_aq_geometry)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_target = QtWidgets.QLabel(self.group_aq_geometry)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_target.setFont(font)
        self.lbl_target.setObjectName("lbl_target")
        self.gridLayout_3.addWidget(self.lbl_target, 0, 0, 1, 1)
        self.lbl_occ_duration = QtWidgets.QLabel(self.group_aq_geometry)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_occ_duration.setFont(font)
        self.lbl_occ_duration.setObjectName("lbl_occ_duration")
        self.gridLayout_3.addWidget(self.lbl_occ_duration, 2, 0, 1, 1)
        self.lbl_eq_radius = QtWidgets.QLabel(self.group_aq_geometry)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_eq_radius.setFont(font)
        self.lbl_eq_radius.setObjectName("lbl_eq_radius")
        self.gridLayout_3.addWidget(self.lbl_eq_radius, 2, 1, 1, 1)
        self.lbl_mission = QtWidgets.QLabel(self.group_aq_geometry)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_mission.setFont(font)
        self.lbl_mission.setObjectName("lbl_mission")
        self.gridLayout_3.addWidget(self.lbl_mission, 0, 1, 1, 1)
        self.lbl_lowest_alt = QtWidgets.QLabel(self.group_aq_geometry)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_lowest_alt.setFont(font)
        self.lbl_lowest_alt.setObjectName("lbl_lowest_alt")
        self.gridLayout_3.addWidget(self.lbl_lowest_alt, 4, 1, 1, 1)
        self.lbl_sc_veolcity = QtWidgets.QLabel(self.group_aq_geometry)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_sc_veolcity.setFont(font)
        self.lbl_sc_veolcity.setObjectName("lbl_sc_veolcity")
        self.gridLayout_3.addWidget(self.lbl_sc_veolcity, 4, 0, 1, 1)
        self.spin_occ_duration = QtWidgets.QDoubleSpinBox(self.group_aq_geometry)
        self.spin_occ_duration.setDecimals(0)
        self.spin_occ_duration.setMaximum(1000.0)
        self.spin_occ_duration.setObjectName("spin_occ_duration")
        self.gridLayout_3.addWidget(self.spin_occ_duration, 3, 0, 1, 1)
        self.spin_eq_radius = QtWidgets.QDoubleSpinBox(self.group_aq_geometry)
        self.spin_eq_radius.setDecimals(0)
        self.spin_eq_radius.setMaximum(100000.0)
        self.spin_eq_radius.setObjectName("spin_eq_radius")
        self.gridLayout_3.addWidget(self.spin_eq_radius, 3, 1, 1, 1)
        self.spin_sc_velocity = QtWidgets.QDoubleSpinBox(self.group_aq_geometry)
        self.spin_sc_velocity.setDecimals(0)
        self.spin_sc_velocity.setMaximum(10000.0)
        self.spin_sc_velocity.setObjectName("spin_sc_velocity")
        self.gridLayout_3.addWidget(self.spin_sc_velocity, 5, 0, 1, 1)
        self.spin_lowest_alt = QtWidgets.QDoubleSpinBox(self.group_aq_geometry)
        self.spin_lowest_alt.setDecimals(0)
        self.spin_lowest_alt.setMaximum(10000.0)
        self.spin_lowest_alt.setObjectName("spin_lowest_alt")
        self.gridLayout_3.addWidget(self.spin_lowest_alt, 5, 1, 1, 1)
        self.line_edit_target = QtWidgets.QLineEdit(self.group_aq_geometry)
        self.line_edit_target.setReadOnly(True)
        self.line_edit_target.setObjectName("line_edit_target")
        self.gridLayout_3.addWidget(self.line_edit_target, 1, 0, 1, 1)
        self.line_edit_mission = QtWidgets.QLineEdit(self.group_aq_geometry)
        self.line_edit_mission.setReadOnly(True)
        self.line_edit_mission.setObjectName("line_edit_mission")
        self.gridLayout_3.addWidget(self.line_edit_mission, 1, 1, 1, 1)
        self.vlayout_left.addWidget(self.group_aq_geometry)
        self.group_radio_analysis = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.group_radio_analysis.setFont(font)
        self.group_radio_analysis.setAlignment(QtCore.Qt.AlignCenter)
        self.group_radio_analysis.setObjectName("group_radio_analysis")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.group_radio_analysis)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_freq_separation = QtWidgets.QLabel(self.group_radio_analysis)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_freq_separation.setFont(font)
        self.lbl_freq_separation.setObjectName("lbl_freq_separation")
        self.gridLayout_4.addWidget(self.lbl_freq_separation, 0, 0, 1, 1)
        self.spin_k_spec = QtWidgets.QDoubleSpinBox(self.group_radio_analysis)
        self.spin_k_spec.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.spin_k_spec.setFont(font)
        self.spin_k_spec.setDecimals(0)
        self.spin_k_spec.setMaximum(1000.0)
        self.spin_k_spec.setObjectName("spin_k_spec")
        self.gridLayout_4.addWidget(self.spin_k_spec, 5, 0, 1, 1)
        self.spin_t_int = QtWidgets.QDoubleSpinBox(self.group_radio_analysis)
        self.spin_t_int.setEnabled(False)
        self.spin_t_int.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_t_int.setDecimals(2)
        self.spin_t_int.setMaximum(1000.0)
        self.spin_t_int.setObjectName("spin_t_int")
        self.gridLayout_4.addWidget(self.spin_t_int, 3, 1, 1, 1)
        self.lbl_k_spec = QtWidgets.QLabel(self.group_radio_analysis)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_k_spec.setFont(font)
        self.lbl_k_spec.setObjectName("lbl_k_spec")
        self.gridLayout_4.addWidget(self.lbl_k_spec, 4, 0, 1, 1)
        self.spin_t_hop = QtWidgets.QDoubleSpinBox(self.group_radio_analysis)
        self.spin_t_hop.setEnabled(False)
        self.spin_t_hop.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_t_hop.setMaximum(1000.0)
        self.spin_t_hop.setObjectName("spin_t_hop")
        self.gridLayout_4.addWidget(self.spin_t_hop, 7, 1, 1, 1)
        self.lbl_t_int = QtWidgets.QLabel(self.group_radio_analysis)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_t_int.setFont(font)
        self.lbl_t_int.setObjectName("lbl_t_int")
        self.gridLayout_4.addWidget(self.lbl_t_int, 2, 1, 1, 1)
        self.spin_timespan = QtWidgets.QDoubleSpinBox(self.group_radio_analysis)
        self.spin_timespan.setEnabled(False)
        self.spin_timespan.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_timespan.setMaximum(1000.0)
        self.spin_timespan.setObjectName("spin_timespan")
        self.gridLayout_4.addWidget(self.spin_timespan, 5, 1, 1, 1)
        self.lbl_freq_res = QtWidgets.QLabel(self.group_radio_analysis)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_freq_res.setFont(font)
        self.lbl_freq_res.setObjectName("lbl_freq_res")
        self.gridLayout_4.addWidget(self.lbl_freq_res, 0, 1, 1, 1)
        self.lbl_timespan = QtWidgets.QLabel(self.group_radio_analysis)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_timespan.setFont(font)
        self.lbl_timespan.setObjectName("lbl_timespan")
        self.gridLayout_4.addWidget(self.lbl_timespan, 4, 1, 1, 1)
        self.lbl_l_win = QtWidgets.QLabel(self.group_radio_analysis)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_l_win.setFont(font)
        self.lbl_l_win.setObjectName("lbl_l_win")
        self.gridLayout_4.addWidget(self.lbl_l_win, 2, 0, 1, 1)
        self.spin_moving_overlap = QtWidgets.QDoubleSpinBox(self.group_radio_analysis)
        self.spin_moving_overlap.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.spin_moving_overlap.setFont(font)
        self.spin_moving_overlap.setDecimals(0)
        self.spin_moving_overlap.setObjectName("spin_moving_overlap")
        self.gridLayout_4.addWidget(self.spin_moving_overlap, 7, 0, 1, 1)
        self.spin_freq_separation = QtWidgets.QDoubleSpinBox(self.group_radio_analysis)
        self.spin_freq_separation.setEnabled(False)
        self.spin_freq_separation.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_freq_separation.setDecimals(0)
        self.spin_freq_separation.setMaximum(1000.0)
        self.spin_freq_separation.setObjectName("spin_freq_separation")
        self.gridLayout_4.addWidget(self.spin_freq_separation, 1, 0, 1, 1)
        self.spin_freq_res = QtWidgets.QDoubleSpinBox(self.group_radio_analysis)
        self.spin_freq_res.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.spin_freq_res.setFont(font)
        self.spin_freq_res.setDecimals(2)
        self.spin_freq_res.setMaximum(1000.0)
        self.spin_freq_res.setSingleStep(0.01)
        self.spin_freq_res.setObjectName("spin_freq_res")
        self.gridLayout_4.addWidget(self.spin_freq_res, 1, 1, 1, 1)
        self.lbl_moving_overlap = QtWidgets.QLabel(self.group_radio_analysis)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_moving_overlap.setFont(font)
        self.lbl_moving_overlap.setObjectName("lbl_moving_overlap")
        self.gridLayout_4.addWidget(self.lbl_moving_overlap, 6, 0, 1, 1)
        self.lbl_t_hop = QtWidgets.QLabel(self.group_radio_analysis)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_t_hop.setFont(font)
        self.lbl_t_hop.setObjectName("lbl_t_hop")
        self.gridLayout_4.addWidget(self.lbl_t_hop, 6, 1, 1, 1)
        self.spin_l_win = QtWidgets.QDoubleSpinBox(self.group_radio_analysis)
        self.spin_l_win.setEnabled(False)
        self.spin_l_win.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_l_win.setDecimals(0)
        self.spin_l_win.setMaximum(1000000.0)
        self.spin_l_win.setObjectName("spin_l_win")
        self.gridLayout_4.addWidget(self.spin_l_win, 3, 0, 1, 1)
        self.vlayout_left.addWidget(self.group_radio_analysis)
        self.group_wind_props = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.group_wind_props.setFont(font)
        self.group_wind_props.setAlignment(QtCore.Qt.AlignCenter)
        self.group_wind_props.setObjectName("group_wind_props")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.group_wind_props)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lbl_xmin = QtWidgets.QLabel(self.group_wind_props)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_xmin.setFont(font)
        self.lbl_xmin.setObjectName("lbl_xmin")
        self.gridLayout_5.addWidget(self.lbl_xmin, 0, 0, 1, 1)
        self.lbl_ymax = QtWidgets.QLabel(self.group_wind_props)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_ymax.setFont(font)
        self.lbl_ymax.setObjectName("lbl_ymax")
        self.gridLayout_5.addWidget(self.lbl_ymax, 2, 1, 1, 1)
        self.lbl_ymin = QtWidgets.QLabel(self.group_wind_props)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_ymin.setFont(font)
        self.lbl_ymin.setObjectName("lbl_ymin")
        self.gridLayout_5.addWidget(self.lbl_ymin, 2, 0, 1, 1)
        self.lbl_xmax = QtWidgets.QLabel(self.group_wind_props)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lbl_xmax.setFont(font)
        self.lbl_xmax.setObjectName("lbl_xmax")
        self.gridLayout_5.addWidget(self.lbl_xmax, 0, 1, 1, 1)
        self.spin_xmin = QtWidgets.QDoubleSpinBox(self.group_wind_props)
        self.spin_xmin.setDecimals(0)
        self.spin_xmin.setMinimum(-10000.0)
        self.spin_xmin.setMaximum(10000.0)
        self.spin_xmin.setObjectName("spin_xmin")
        self.gridLayout_5.addWidget(self.spin_xmin, 1, 0, 1, 1)
        self.spin_xmax = QtWidgets.QDoubleSpinBox(self.group_wind_props)
        self.spin_xmax.setDecimals(0)
        self.spin_xmax.setMinimum(-10000.0)
        self.spin_xmax.setMaximum(10000.0)
        self.spin_xmax.setObjectName("spin_xmax")
        self.gridLayout_5.addWidget(self.spin_xmax, 1, 1, 1, 1)
        self.spin_ymin = QtWidgets.QDoubleSpinBox(self.group_wind_props)
        self.spin_ymin.setDecimals(0)
        self.spin_ymin.setMinimum(-1000.0)
        self.spin_ymin.setMaximum(1000.0)
        self.spin_ymin.setObjectName("spin_ymin")
        self.gridLayout_5.addWidget(self.spin_ymin, 3, 0, 1, 1)
        self.spin_ymax = QtWidgets.QDoubleSpinBox(self.group_wind_props)
        self.spin_ymax.setDecimals(0)
        self.spin_ymax.setMinimum(-1000.0)
        self.spin_ymax.setMaximum(1000.0)
        self.spin_ymax.setObjectName("spin_ymax")
        self.gridLayout_5.addWidget(self.spin_ymax, 3, 1, 1, 1)
        self.vlayout_left.addWidget(self.group_wind_props)
        self.group_ani_playback = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.group_ani_playback.setFont(font)
        self.group_ani_playback.setAlignment(QtCore.Qt.AlignCenter)
        self.group_ani_playback.setObjectName("group_ani_playback")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_ani_playback)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spin_ani_speed = QtWidgets.QDoubleSpinBox(self.group_ani_playback)
        self.spin_ani_speed.setDecimals(2)
        self.spin_ani_speed.setMaximum(10.0)
        self.spin_ani_speed.setObjectName("spin_ani_speed")
        self.gridLayout_2.addWidget(self.spin_ani_speed, 1, 1, 1, 1)
        self.spin_start_sec = QtWidgets.QDoubleSpinBox(self.group_ani_playback)
        self.spin_start_sec.setDecimals(0)
        self.spin_start_sec.setObjectName("spin_start_sec")
        self.gridLayout_2.addWidget(self.spin_start_sec, 1, 0, 1, 1)
        self.lbl_start_sec = QtWidgets.QLabel(self.group_ani_playback)
        self.lbl_start_sec.setObjectName("lbl_start_sec")
        self.gridLayout_2.addWidget(self.lbl_start_sec, 0, 0, 1, 1)
        self.lbl_ani_speed = QtWidgets.QLabel(self.group_ani_playback)
        self.lbl_ani_speed.setObjectName("lbl_ani_speed")
        self.gridLayout_2.addWidget(self.lbl_ani_speed, 0, 1, 1, 1)
        self.vlayout_left.addWidget(self.group_ani_playback)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlayout_left.addItem(spacerItem1)
        self.btn_apply_changes = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btn_apply_changes.setFont(font)
        self.btn_apply_changes.setObjectName("btn_apply_changes")
        self.vlayout_left.addWidget(self.btn_apply_changes)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlayout_left.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.vlayout_left)
        self.vline_center_divider = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.vline_center_divider.setFont(font)
        self.vline_center_divider.setFrameShape(QtWidgets.QFrame.VLine)
        self.vline_center_divider.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline_center_divider.setObjectName("vline_center_divider")
        self.horizontalLayout.addWidget(self.vline_center_divider)
        self.vlayout_right = QtWidgets.QVBoxLayout()
        self.vlayout_right.setObjectName("vlayout_right")
        self.lbl_graph_header = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.lbl_graph_header.setFont(font)
        self.lbl_graph_header.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_graph_header.setObjectName("lbl_graph_header")
        self.vlayout_right.addWidget(self.lbl_graph_header)
        self.animation_widget = BSRAnimation(self.centralwidget)
        self.animation_widget.setObjectName("animation_widget")
        self.vlayout_right.addWidget(self.animation_widget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btn_prev_frame = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_prev_frame.setFont(font)
        self.btn_prev_frame.setObjectName("btn_prev_frame")
        self.horizontalLayout_3.addWidget(self.btn_prev_frame)
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_play.setFont(font)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout_3.addWidget(self.btn_play)
        self.btn_pause = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_pause.setFont(font)
        self.btn_pause.setObjectName("btn_pause")
        self.horizontalLayout_3.addWidget(self.btn_pause)
        self.btn_next_frame = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_next_frame.setFont(font)
        self.btn_next_frame.setObjectName("btn_next_frame")
        self.horizontalLayout_3.addWidget(self.btn_next_frame)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.vlayout_right.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.btn_export = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btn_export.setFont(font)
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout_5.addWidget(self.btn_export)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.vlayout_right.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.vlayout_right)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 5)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1325, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionView = QtWidgets.QAction(MainWindow)
        self.actionView.setObjectName("actionView")
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_back.setText(_translate("MainWindow", "Back"))
        self.group_aq_geometry.setTitle(_translate("MainWindow", "Acquisition Geometry"))
        self.lbl_target.setText(_translate("MainWindow", "Target"))
        self.lbl_occ_duration.setText(_translate("MainWindow", "Occultation Duration (min)"))
        self.lbl_eq_radius.setText(_translate("MainWindow", "Equatorial Radius (km)"))
        self.lbl_mission.setText(_translate("MainWindow", "Mission"))
        self.lbl_lowest_alt.setText(_translate("MainWindow", "Lowest Altitude (km)"))
        self.lbl_sc_veolcity.setText(_translate("MainWindow", "S/C Velocity (m/s)"))
        self.group_radio_analysis.setTitle(_translate("MainWindow", "Radio Data Analysis "))
        self.lbl_freq_separation.setText(_translate("MainWindow", "Calc. freq. separation (Hz)"))
        self.lbl_k_spec.setText(_translate("MainWindow", "K (# spectra per plot)"))
        self.lbl_t_int.setText(_translate("MainWindow", "t-int (seconds per FFT)"))
        self.lbl_freq_res.setText(_translate("MainWindow", "Freq. resolution (Hz)"))
        self.lbl_timespan.setText(_translate("MainWindow", "Timespan per plot (sec)"))
        self.lbl_l_win.setText(_translate("MainWindow", "L (# samples per FFT)"))
        self.spin_moving_overlap.setSuffix(_translate("MainWindow", " %"))
        self.lbl_moving_overlap.setText(_translate("MainWindow", "Moving average overlap"))
        self.lbl_t_hop.setText(_translate("MainWindow", "t_hop (overlap in sec)"))
        self.group_wind_props.setTitle(_translate("MainWindow", "Window Properties"))
        self.lbl_xmin.setText(_translate("MainWindow", "X-Axis min (Hz):"))
        self.lbl_ymax.setText(_translate("MainWindow", "Y-Axis max (dB)"))
        self.lbl_ymin.setText(_translate("MainWindow", "Y-Axis min (dB):"))
        self.lbl_xmax.setText(_translate("MainWindow", "X-Axis max (Hz):"))
        self.group_ani_playback.setTitle(_translate("MainWindow", "Animation Playback"))
        self.lbl_start_sec.setText(_translate("MainWindow", "Start Second in File"))
        self.lbl_ani_speed.setText(_translate("MainWindow", "Animation Speed (fps)"))
        self.btn_apply_changes.setText(_translate("MainWindow", "Apply Changes"))
        self.lbl_graph_header.setText(_translate("MainWindow", "Output Power Spectra"))
        self.btn_prev_frame.setText(_translate("MainWindow", "<  Skip Frame"))
        self.btn_play.setText(_translate("MainWindow", "Play"))
        self.btn_pause.setText(_translate("MainWindow", "Pause"))
        self.btn_next_frame.setText(_translate("MainWindow", "Skip Frame  >"))
        self.btn_export.setText(_translate("MainWindow", "Export..."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionView.setText(_translate("MainWindow", "View"))

from animation import BSRAnimation
